language: node_js
node_js:
- '8'
after_success:
- yarn lint || echo "Let's show the lint output here but we don't want it cause a failure yet"
- yarn report-coverage
deploy:
  provider: npm
  email: peter@terascope.io
  api_key:
    secure: "GWfsk/+N7nnfCPUo5+bjkE7HoffJ+G0dJ55P1IULQT3IAvWalxyikP4T/tMONLTuHB3vfmAzQ2rL5DoEP+ryyUAIQfbHL0PR4fe3mOckXKhcoXomY52NxcEFzqnt0Du/HO3o5TiaedXIsclsHLX6JmlVi9DousDb97DdojElG6QbeDuDqc3YuegwYddFt3kyf62WLrt3fH5OEH/OuVk3+Gcpy6ab/Ei+dsuTUDGmyjl2dvrn04TYKi8UXEcaLnyKiSiLZhsl25V9abwT9xXQszjcIwlDwpQYN2hYuxv3cBtpULz0KsLveSkKfabSfKQlUqR/u1S5UU+oUDVC5/ufogDI2VcQBJvZr9QeqPGVcfK+iZoyo99bvYN4mWFcCWeWyidwjST0mYbjKb1Lzwdc1PJ1k0IC/beCl0PL0XZ+Bb4dsKX/e+TaAyFfGpa45UpIl+bRQJg8yLThAN45/TfbaZFR0F3Dgoq1kT1sM57uWLBYpfrfZqvArvtEhczdmwZ64ZEJT6zO+ew6mL/Qw/wzO4CJlki5lajECG+mAmgPbII6gMYNDwT98UTgldnQLsps/UaWeegGAnrHcQ7FKxE375y1PjfML9hUzV1gQT/MQMXtVTG/G0nsm0R+Jj967fpHCdL9vvcJKB07pUI1cyhrM8NrnZ4JOeTVENaMMssLYbY="
  on:
    branch: master
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
    repo: terascope/chunked-file-reader
